apiVersion: v1
kind: Pod
metadata:
  name: kafkaclient
  namespace: kafka
spec:
  containers:
  - name: kafka
    image: solsson/kafka:0.11.0.0
    # volumeMounts:
    #   - name: cert-volume
    #     mountPath: /etc/cert-volume
    command:
     - sh
     - -c
     - exec tail -f /dev/null
  # volumes:
  #   - name: cert-volume
  #     secret:
  #       secretName: <cluster-name>-cluster-ca-cert
